name: TrollMasterPlusPlus
version: 1.0
main: me.neo_0815.trollmaster.TrollMasterPlusPlus
description: Ein TrollPlugin
author: neo_0815

commands:
     trollmode:
          description: Aktiviert den Trollmode.
          usage: /trollmode
          aliases: [tm]
     trollmodeoff:
          description: Deaktiviert den Trollmode.
          usage: /trollmodeoff
          aliases: [tmoff ,tmo]
     trollspawn:
          description: Spawnt das angegebene Entity.
          usage: /trollspawn <Entity>
          aliases: [trollsummon ,ts ,tmspawn ,tmsummon]
     trolljoin:
          description: Spawnt das angegebene Entity.
          usage: /trolljoin <Name>
          aliases: [tj ,tmjoin ,tmj]
     trollleave:
          description: Spawnt das angegebene Entity.
          usage: /trollleave <Name>
          aliases: [tl ,tmleave ,tml]